version: "3.9"
services: 
  api:
    depends_on:
      - "postgres"
    build: .
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_SERVICE_SERVICE_HOST=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=postgres
      - POSGRES_DB=softconapi
      - POSTGRES_SERVICE_SERVICE_PORT=5432
  
  
  postgres:
    image: postgres
    ports: 
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: example
